# -*- coding: utf-8 -*-
"""tier_script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LmSLOmnklnyPn0W0DQOv59Lxcqmk9Aco
"""

import pandas as pd

df = pd.read_excel("./../Original-data/dem_score.xlsx")
df.head()

assert not df.isnull().values.any()

assert df.duplicated().eq(False).all()

df.columns[1:]

melted_df = df.melt(id_vars=["country"], 
        var_name="Year", 
        value_name="demography score")

sorted_df = melted_df.sort_values(by=['country', 'Year']).reset_index(drop=True)

sorted_df.to_csv('./../Analysis-data/processed_data.csv')